encoding: UTF-8
# Site
repository: iizzzz/iizzzz.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 신건우
title: 백엔드 개발자
email: relicaset02@gmail.com
website: https://root-ca.tistory.com/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  iizzzz
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Devops를 꿈꾸며 개발 능력 보유를 위해 20주 과정 웹 개발 부트캠프 코드스테이츠를 수료하였습니다.
  수료 후 기본만 잘하자는 마인드로 취업하기 전까지 열심히 준비 중 입니다.

  - [ Language ] Java
  - [ Framework & Library ] Spring Boot, Spring Data JPA, JWT, OAuth2
  - [ DataBase ] Mysql, MariaDB
  - [ Linux ] Docker, Kubernetes
  - [ Tools ] Git, AWS(EC2, RDS, S3), Jira

  - 블로그 : root-ca.tistory.com
  
  Spring Boot기반 Spring Data JPA & JWT를 활용한 웹 개발
  RDB & AWS 와 Github Actions을 이용한 CI/CD 구축
  2회의 협업 프로젝트 경험

content:
  - title: 프로젝트 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Tea Time project
        link: 배포링크 > http://project-teatime-dev.s3-website.ap-northeast-2.amazonaws.com/
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          코드스테이츠 메인 프로젝트 (6인 / 4주)
        description: | # this will include new lines to allow paragraphs
          팀원, 백엔드 : Spring Boot, JPA, JWT, Mysql, AWS
          | 2023.01 - 2023.02
          요구사항 정의서 & DB ERD & API 명세서 작성
          JWT 토큰 기반 인증 구현
          AWS S3, RDS & Github Actions를 이용한 CI/CD 구축

  - title: 경험 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 고은정보기술
#        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 기술지원팀 시스템 엔지니어/주임
        caption: 2021.10 - 2022.07
        quote: >

        description: | # this will include new lines to allow paragraphs
            | 서버 구축 및 마운트 & 원격 유지보수 & 데이터 이전 업무 & Fortinet 방화벽 설정 등 인프라 관련 직무를 수행하였습니다.

  - title: 학력 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 덕수고등학교
        caption: 2010 - 2013
        sub_title: 문과

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

